// Email summary integration via Web3Forms (free, no backend).

const WEB3FORMS_ENDPOINT = 'https://api.web3forms.com/submit'

export interface EmailPreferences {
  enabled: boolean
  accessKey: string
  email: string
  frequency: 'daily' | 'weekly'
  includeForecast: boolean
  includeDisasters: boolean
  includeRisk: boolean
}

const STORAGE_KEY = 'wx.emailPrefs'

export function loadEmailPrefs(): EmailPreferences {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) return JSON.parse(raw)
  } catch { /* ignore */ }
  return {
    enabled: false,
    accessKey: '',
    email: '',
    frequency: 'daily',
    includeForecast: true,
    includeDisasters: true,
    includeRisk: true,
  }
}

export function saveEmailPrefs(prefs: EmailPreferences) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(prefs))
  } catch { /* ignore */ }
}

export interface SummaryPayload {
  location: string
  date: string
  temperature: string
  condition: string
  wind: string
  humidity: string
  riskScore?: number
  riskLabel?: string
  disasterCount: number
  topDisasters: string[]
}

export async function sendEmailSummary(
  prefs: EmailPreferences,
  payload: SummaryPayload,
): Promise<{ success: boolean; message: string }> {
  if (!prefs.accessKey || !prefs.email) {
    return { success: false, message: 'Missing access key or email.' }
  }

  const htmlParts: string[] = []
  htmlParts.push(`<h2>Weatherly Daily Summary — ${payload.location}</h2>`)
  htmlParts.push(`<p><strong>Date:</strong> ${payload.date}</p>`)
  htmlParts.push(`<p><strong>Condition:</strong> ${payload.condition}</p>`)
  htmlParts.push(`<p><strong>Temperature:</strong> ${payload.temperature}</p>`)
  htmlParts.push(`<p><strong>Wind:</strong> ${payload.wind}</p>`)
  htmlParts.push(`<p><strong>Humidity:</strong> ${payload.humidity}</p>`)

  if (prefs.includeRisk && payload.riskScore != null) {
    htmlParts.push(`<p><strong>Risk Score:</strong> ${payload.riskScore}/100 — ${payload.riskLabel}</p>`)
  }

  if (prefs.includeDisasters && payload.disasterCount > 0) {
    htmlParts.push(`<h3>Active Disasters (${payload.disasterCount})</h3>`)
    htmlParts.push(`<ul>${payload.topDisasters.map((d) => `<li>${d}</li>`).join('')}</ul>`)
  }

  htmlParts.push(`<hr><p style="color:#94a3b8;font-size:12px">Generated by Weatherly · Data by Open-Meteo</p>`)

  try {
    const res = await fetch(WEB3FORMS_ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        access_key: prefs.accessKey,
        to: prefs.email,
        subject: `Weatherly Summary — ${payload.location} — ${payload.date}`,
        from_name: 'Weatherly',
        html: htmlParts.join('\n'),
      }),
    })

    const data = await res.json()
    if (data.success) {
      return { success: true, message: 'Summary sent!' }
    }
    return { success: false, message: data.message || 'Failed to send.' }
  } catch (err) {
    return { success: false, message: 'Network error.' }
  }
}
